[package]
name = "bench_rust"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]

[dependencies]
rayon_adaptive = {git = "https://github.com/wagnerf42/rayon-adaptive.git", branch = "lifetimes_smr"} 
par-sort = {path = "../.."}
rand = "*"
rayon = "*"
